### ISSUE TITLE
Split out logic and add login page

### ISSUE THREAD

**Issue by zjordan16** [zjordan16/Handicap-Calculator#1]
https://gist.github.com/yelluw/0acee8e651a898f5eb46d8d2a577578c

Here is an example.

**Comment by byork6** [comment]
Fix second argument issue for validate_login method.
Clean up login page formatting

**Comment by byork6** [comment]
Potential clue for unused parameter issue

Why the Extra Parameter is Required
In GUI frameworks, event handlers often need to accept parameters that provide context about the event that occurred. For instance:

Event Object: This parameter can include details about the event, such as the source of the event, additional metadata, etc.
Consistency: By defining an event handler with a specific signature, the framework ensures that it can call the handler with the expected arguments.
How to Handle This
Keep the Parameter:

Even if you don’t use the parameter in your method, keep it in the method signature to ensure that the framework can call your handler correctly.
Ignore the Parameter:

You can use an underscore (_) as the parameter name to indicate that it’s intentionally unused. This is a common practice to avoid linting warnings about unused parameters.

**Comment by byork6** [comment]
Snippet of example from beeware documentation showing "widget" named used for the parameter

  button = toga.Button(
            "Say Hello!",
            on_press=self.say_hello,
            style=Pack(padding=5),
        )

        main_box.add(name_box)
        main_box.add(button)

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()

    def say_hello(self, widget):
        print(f"Hello, {self.name_input.value}")

**Comment by byork6** [comment]
Parameter required by Beeware Toga framework, shows what widget type that triggered the event and also shows the memory location of the instance of the widget used.

**Comment by byork6** [comment]
![image](https://github.com/user-attachments/assets/9329828f-b47d-491b-809a-107c097bd52b)
add usga image centered on login page

**Comment by byork6** [comment]
https://github.com/beeware/toga/issues/2142

**Comment by byork6** [comment]
https://toga.readthedocs.io/en/latest/reference/api/widgets/imageview.html
this documentation should be helpful

**Comment by byork6** [comment]
Image and input boxes adjust size and spacing dynamically when changing between windowed and full screen mode.
